# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Data-Pageset
version:      1.04
version_from: lib/Data/Pageset.pm
installdirs:  site
requires:
    Data::Page:                    2
    Test::More:                    0.1

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
resources:
    repository: https://github.com/ranguard/data-pageset.git
